// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CanvasThing$ReactTemplate = require("./CanvasThing.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, CanvasThing$ReactTemplate.make(/* array */[])), "index1");

/*  Not a pure module */
